# Generated by Django 3.0.2 on 2020-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_queuer_roll_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuer",
            name="roll_number",
            field=models.CharField(max_length=10),
        ),
    ]
