# Generated by Django 3.0.2 on 2020-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_auto_20200118_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuer",
            name="proof_document",
            field=models.FileField(default="abc", upload_to="user_directory_path"),
        ),
        migrations.AddField(
            model_name="queuer",
            name="wife_name",
            field=models.CharField(
                default="Did not disclose. Please contact again", max_length=126
            ),
        ),
    ]
