# Generated by Django 3.0.2 on 2020-01-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_auto_20200121_1841"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="queuer",
            unique_together={("name", "roll_number", "building_applied")},
        ),
    ]
