# Generated by Django 3.0.2 on 2020-02-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_auto_20200121_1918"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queuer", old_name="wife_name", new_name="spouse_name",
        ),
    ]
