# Generated by Django 3.0.2 on 2020-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_auto_20200204_1832"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queuer",
            old_name="proof_document",
            new_name="marriage_certificate",
        ),
        migrations.AddField(
            model_name="queuer",
            name="aadhaar_card_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuer",
            name="institute_ID_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuer",
            name="marriage_certificate_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuer",
            name="spouse_aadhaar_card",
            field=models.FileField(
                default="no entry", upload_to="spouse_aadhaar_card/"
            ),
        ),
        migrations.AddField(
            model_name="queuer",
            name="spouse_aadhaar_card_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuer",
            name="your_aadhaar_card",
            field=models.FileField(default="no entry", upload_to="your_aadhaar_card/"),
        ),
    ]
