# Generated by Django 3.0.2 on 2020-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_auto_20200204_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuer",
            name="spouse_aadhaar_card",
            field=models.FileField(upload_to="spouse_aadhaar_card/"),
        ),
        migrations.AlterField(
            model_name="queuer",
            name="your_aadhaar_card",
            field=models.FileField(upload_to="your_aadhaar_card/"),
        ),
    ]
