# Generated by Django 3.0.2 on 2020-02-04 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_auto_20200204_1900"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuer",
            name="date_applied",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
