# Generated by Django 3.0.2 on 2020-02-14 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_queuer_date_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuer",
            name="room_number_if_placed",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="queuer",
            name="verified_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuer",
            name="date_applied",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="queuer",
            name="waitlist_number",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
