# Generated by Django 3.0.7 on 2020-09-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20200215_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='queuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Queuer'),
        ),
        migrations.AddField(
            model_name='queuer',
            name='waitlist_MRSB',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='queuer',
            name='waitlist_Tulsi',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='queuer',
            name='waitlist_Type1',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='queuer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='building_applied',
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='waitlist_number',
        ),
    ]
