# Generated by Django 3.0.7 on 2020-09-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200919_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='queuer',
        ),
        migrations.AddField(
            model_name='queuer',
            name='mrsb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MRSB', to='portal.Building'),
        ),
        migrations.AddField(
            model_name='queuer',
            name='tulsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tulsi', to='portal.Building'),
        ),
        migrations.AddField(
            model_name='queuer',
            name='type1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Type1', to='portal.Building'),
        ),
        migrations.AlterUniqueTogether(
            name='queuer',
            unique_together={('name', 'roll_number', 'mrsb')},
        ),
    ]
