# Generated by Django 3.0.7 on 2020-09-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20200919_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuer',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.Building'),
        ),
        migrations.AlterUniqueTogether(
            name='queuer',
            unique_together={('roll_number', 'building')},
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='mrsb',
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='tulsi',
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='type1',
        ),
    ]
