# Generated by Django 3.0.7 on 2020-09-20 17:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200919_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('photo', models.FileField(upload_to='dependants/')),
                ('queuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Queuer')),
            ],
            options={
                'verbose_name': 'Dependant',
                'verbose_name_plural': 'Dependants',
            },
        ),
    ]
