# Generated by Django 3.0.7 on 2020-09-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_dependant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='photo',
            field=models.FileField(blank=True, upload_to='dependants/'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='queuer',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='portal.Queuer'),
        ),
    ]
