# Generated by Django 3.0.7 on 2020-09-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200920_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependant',
            name='queuer',
        ),
        migrations.AddField(
            model_name='queuer',
            name='dependant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Dependant'),
        ),
    ]
