# Generated by Django 3.0.7 on 2020-09-21 19:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20200921_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_certificate', models.FileField(upload_to='marriage_certificates/')),
                ('pic_with_spouse', models.FileField(upload_to='photo_with_spouse/')),
                ('coursework_grade_sheet', models.FileField(upload_to='grade_sheet/')),
                ('recommendation_of_guide', models.FileField(upload_to='guide_recommendation/')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='dependant',
        ),
        migrations.AddField(
            model_name='dependant',
            name='queuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Queuer'),
        ),
        migrations.AddField(
            model_name='dependant',
            name='relation',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('FIL', 'Father-in-Law'), ('MIL', 'Mother-in-Law'), ('C', 'Child')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='queuer',
            name='scholarship',
            field=models.CharField(choices=[('I', 'Institute'), ('CSIR', 'CSIR'), ('UGC', 'UGC'), ('None', 'None')], default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='queuer',
            name='scholarship_start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('roll_no', models.CharField(max_length=128)),
                ('date_of_registration', models.DateField()),
                ('department', models.CharField(help_text="For example, 'Energy Science and Engineering'", max_length=128)),
                ('date_of_marriage', models.DateField(null=True)),
                ('email', models.EmailField(max_length=256)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('permanent_address', models.TextField(default='')),
                ('scholarship', models.CharField(choices=[('I', 'Institute'), ('CSIR', 'CSIR'), ('UGC', 'UGC')], max_length=128, null=True)),
                ('date_of_scholarship', models.DateField(null=True)),
                ('course_work_completed_on', models.DateField(help_text='Give the expected date')),
                ('course_work_completed_by', models.CharField(max_length=128)),
                ('attachments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Attachment', unique=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'unique_together': {('roll_no', 'attachments')},
            },
        ),
    ]
