# Generated by Django 3.0.7 on 2020-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20200922_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='coursework_grade_sheet',
            field=models.FileField(null=True, upload_to='grade_sheet/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='marriage_certificate',
            field=models.FileField(null=True, upload_to='marriage_certificates/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='pic_with_spouse',
            field=models.FileField(null=True, upload_to='photo_with_spouse/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='recommendation_of_guide',
            field=models.FileField(null=True, upload_to='guide_recommendation/'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
