# Generated by Django 3.0.7 on 2020-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20200922_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='pic_with_spouse',
            new_name='joint_photograph_with_spouse',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='recommendation_of_guide',
            new_name='recommendation_of_guide_for_accomodation',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='course_work_completed_on',
            field=models.DateField(default='', help_text='Give the expected date', null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_of_marriage',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_of_scholarship',
            field=models.DateField(default='', null=True),
        ),
    ]
