# Generated by Django 3.0.7 on 2020-09-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20200922_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='roll_no',
            new_name='roll_number',
        ),
    ]
