# Generated by Django 3.1.1 on 2020-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_applicant_spouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='spouse_designation',
            field=models.CharField(default='N/A', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='spouse_roll_number',
            field=models.CharField(default='N/A', max_length=128, null=True),
        ),
    ]
