# Generated by Django 3.1.1 on 2020-10-02 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20201002_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_of_marriage',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
