# Generated by Django 3.1.1 on 2020-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20201002_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='coursework_grade_sheet_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='joint_photograph_with_spouse_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='marriage_certificate_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='recommendation_of_guide_for_accomodation_verified',
            field=models.BooleanField(default=False),
        ),
    ]
