# Generated by Django 3.1.1 on 2020-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20201010_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
