# Generated by Django 3.1.1 on 2020-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_applicant_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='waitlist_MRSB',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='waitlist_Tulsi',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='waitlist_Type1',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
