# Generated by Django 3.1.1 on 2020-10-10 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20201010_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
