# Generated by Django 3.1.1 on 2020-10-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_applicant_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
