# Generated by Django 3.1.1 on 2020-10-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_applicant_verified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.building'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
