# Generated by Django 3.1.1 on 2020-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20201010_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='coursework_grade_sheet',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='joint_photograph_with_spouse',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='marriage_certificate',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='recommendation_of_guide_for_accomodation',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='waitlist_Type1',
            field=models.IntegerField(db_index=True, default='0', editable=False),
        ),
    ]
