# Generated by Django 3.1.1 on 2020-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20201010_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
