# Generated by Django 3.1.1 on 2020-10-10 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_applicant_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 13, 53, 3, 375611, tzinfo=utc), editable=False),
        ),
    ]
