# Generated by Django 3.1.1 on 2020-10-10 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20201010_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='verified',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 13, 54, 28, 676203, tzinfo=utc), editable=False),
        ),
    ]
