# Generated by Django 3.1.1 on 2020-10-10 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20201010_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 14, 14, 34, 419410, tzinfo=utc), editable=False),
        ),
    ]
