# Generated by Django 3.1.1 on 2020-10-10 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_auto_20201010_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 4, 59, 541564, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(blank=True, default='Verified!', null=True),
        ),
    ]
