# Generated by Django 3.0.7 on 2020-10-11 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20201010_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 7, 54, 21, 418007, tzinfo=utc), editable=False),
        ),
    ]
