# Generated by Django 3.0.7 on 2020-10-11 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20201011_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
