# Generated by Django 3.0.7 on 2020-10-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20201011_1324'),
        ('portal', '0043_auto_20201011_1329'),
    ]

    operations = [
    ]
