# Generated by Django 3.0.7 on 2020-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20201012_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='vacate',
            field=models.BooleanField(default=False),
        ),
    ]
