# Generated by Django 3.0.7 on 2020-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_applicant_vacate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(blank=True, default='Your Documents are not yet verified!', null=True),
        ),
    ]
