# Generated by Django 3.0.7 on 2020-10-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_auto_20201015_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='vacate',
        ),
    ]
