# Generated by Django 3.0.7 on 2020-10-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_auto_20201016_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependant',
            name='queuer',
        ),
        migrations.AlterUniqueTogether(
            name='queuer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='queuer',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Dependant',
        ),
        migrations.DeleteModel(
            name='Queuer',
        ),
    ]
