# Generated by Django 3.0.7 on 2020-10-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_auto_20201016_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='notif_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
