# Generated by Django 3.0.7 on 2020-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_applicant_notif_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='notif_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
