# Generated by Django 3.0.7 on 2020-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0052_auto_20201016_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='notif_sent',
        ),
        migrations.AddField(
            model_name='applicant',
            name='defer',
            field=models.BooleanField(default=True),
        ),
    ]
