# Generated by Django 3.0.7 on 2020-10-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_auto_20201016_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='defer',
        ),
        migrations.AddField(
            model_name='applicant',
            name='defer_MRSB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='defer_Tulsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='defer_Type1',
            field=models.BooleanField(default=False),
        ),
    ]
