# Generated by Django 3.0.7 on 2020-10-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_auto_20201016_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('date_of_marriage', models.DateField(default='', null=True)),
                ('marriage_certificate', models.FileField(null=True, upload_to='marriage_certificates/')),
                ('joint_photograph_with_spouse', models.FileField(null=True, upload_to='photo_with_spouse/')),
                ('coursework_grade_sheet', models.FileField(null=True, upload_to='grade_sheet/')),
                ('recommendation_of_guide_for_accomodation', models.FileField(null=True, upload_to='guide_recommendation/')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Applicant')),
            ],
        ),
    ]
