# Generated by Django 3.0.7 on 2020-10-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='spouse_designation',
            field=models.CharField(default='N/A', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='spouse_name',
            field=models.CharField(default='Spouse', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='spouse_roll_number',
            field=models.CharField(default='N/A', max_length=128, null=True),
        ),
    ]
