# Generated by Django 3.0.7 on 2020-10-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_auto_20201019_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='applicant',
            new_name='applic',
        ),
    ]
