# Generated by Django 3.0.7 on 2020-10-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0058_auto_20201019_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='applic',
            new_name='applicant',
        ),
    ]
