# Generated by Django 3.0.7 on 2020-10-21 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0059_auto_20201020_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='scholar_awarded_upto',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scholarship Awarded Upto'),
        ),
    ]
