# Generated by Django 3.0.7 on 2020-12-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0060_applicant_scholar_awarded_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='coursework_grade_sheet',
            field=models.FileField(null=True, upload_to='grade_sheet/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='coursework_grade_sheet_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='joint_photograph_with_spouse',
            field=models.FileField(null=True, upload_to='photo_with_spouse/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='joint_photograph_with_spouse_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='marriage_certificate',
            field=models.FileField(null=True, upload_to='marriage_certificates/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='marriage_certificate_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='recommendation_of_guide_for_accomodation',
            field=models.FileField(null=True, upload_to='guide_recommendation/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='recommendation_of_guide_for_accomodation_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='spouse_designation',
            field=models.CharField(default='N/A', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='spouse_name',
            field=models.CharField(default='Spouse', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='spouse_roll_number',
            field=models.CharField(default='N/A', max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
