# Generated by Django 3.0.7 on 2020-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0062_auto_20201213_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='acad_details_verified',
            field=models.BooleanField(default=False),
        ),
    ]
