# Generated by Django 3.0.7 on 2020-12-13 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0063_auto_20201213_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='acad_details_verification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verification Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='acad_details_verified',
            field=models.BooleanField(default=False, verbose_name='The academic details are verified and found correct'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='scholar_awarded_upto',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Initially the scholarship awarded up to'),
        ),
    ]
