# Generated by Django 3.0.7 on 2020-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0064_auto_20201213_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='scholarship',
            field=models.CharField(choices=[('I', 'Institute'), ('CSIR', 'CSIR'), ('UGC', 'UGC')], max_length=128, null=True, verbose_name='Scholarship: Institute / CSIR / UGC'),
        ),
    ]
