# Generated by Django 3.0.7 on 2020-12-13 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0065_auto_20201213_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='application_received_by_hcu_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Received by H.C.Unit Date:'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_of_scholarship',
            field=models.DateField(default='', null=True, verbose_name='Date from which scholarship is awarded'),
        ),
    ]
