# Generated by Django 3.0.7 on 2020-12-13 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0067_auto_20201213_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='acad_details_verification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verification Date by Academic Section'),
        ),
    ]
