# Generated by Django 3.0.7 on 2020-12-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0070_auto_20201213_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='scholarship_awarded_upto',
            field=models.DateField(default='', verbose_name='Initially the scholarship awarded up to'),
        ),
    ]
