# Generated by Django 3.0.7 on 2020-12-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0071_auto_20201213_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='scholarship_awarded_upto',
            field=models.DateField(default='', null=True, verbose_name='Initially the scholarship awarded up to'),
        ),
    ]
