# Generated by Django 3.0.7 on 2020-12-13 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0074_auto_20201213_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_received_by_hcu_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Application Received by H.C.Unit Date:'),
        ),
    ]
