# Generated by Django 3.0.7 on 2020-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0075_auto_20201213_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='waitlist_Type1',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
