# Generated by Django 3.0.7 on 2020-12-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0077_auto_20201215_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=125, unique=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Applicant')),
            ],
        ),
    ]
