# Generated by Django 3.0.7 on 2020-12-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0078_waitlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='applicant',
        ),
    ]
