# Generated by Django 3.0.7 on 2020-12-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0079_remove_waitlist_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='applicant',
            field=models.ManyToManyField(to='portal.Applicant'),
        ),
    ]
