# Generated by Django 3.0.7 on 2020-12-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0080_waitlist_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupiedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=125, unique=True)),
                ('applicant', models.ManyToManyField(to='portal.Applicant')),
            ],
        ),
    ]
