# Generated by Django 3.0.7 on 2020-12-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0081_occupiedlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupiedlist',
            options={'verbose_name': 'Occupied List', 'verbose_name_plural': 'Occupied Lists'},
        ),
    ]
