# Generated by Django 3.0.7 on 2020-12-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0082_auto_20201224_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmails',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.occupiedlist',),
        ),
    ]
