# Generated by Django 3.0.7 on 2020-12-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0083_sendemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='applicant',
            field=models.ManyToManyField(blank=True, to='portal.Applicant'),
        ),
    ]
