# Generated by Django 3.0.7 on 2020-12-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0084_auto_20201224_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmails',
        ),
        migrations.AlterField(
            model_name='occupiedlist',
            name='applicant',
            field=models.ManyToManyField(blank=True, to='portal.Applicant'),
        ),
    ]
