# Generated by Django 3.0.7 on 2020-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0085_auto_20201224_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacatedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=125, unique=True)),
                ('applicant', models.ManyToManyField(blank=True, to='portal.Applicant')),
            ],
        ),
    ]
