# Generated by Django 3.1.4 on 2020-12-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0086_vacatedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='acadsection_feedback',
            field=models.TextField(blank=True, default='Your Documents are not yet verified!', null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='spouse_name',
            field=models.CharField(default='Name of your Spouse', max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set(),
        ),
    ]
