# Generated by Django 3.1.4 on 2020-12-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0088_auto_20201225_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='defer_MRSB',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='defer_Tulsi',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='defer_Type1',
        ),
    ]
