# Generated by Django 3.1.4 on 2020-12-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0089_auto_20201226_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={'verbose_name': 'Buffered', 'verbose_name_plural': 'Buffered'},
        ),
    ]
