# Generated by Django 3.1.4 on 2020-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0091_auto_20201226_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='waitlist_MRSB',
            field=models.IntegerField(db_index=True, default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='waitlist_Tulsi',
            field=models.IntegerField(db_index=True, default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='waitlist_Type1',
            field=models.IntegerField(db_index=True, default=-1, editable=False),
        ),
    ]
