# Generated by Django 3.1.4 on 2020-12-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0092_auto_20201227_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='defer_MRSB',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='defer_Tulsi',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='defer_Type1',
        ),
    ]
