# Generated by Django 3.0.2 on 2020-01-16 06:14

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                ("occupancy", models.IntegerField(default=800)),
            ],
            options={"verbose_name": "building", "verbose_name_plural": "buildings",},
        ),
        migrations.CreateModel(
            name="Queuer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=126)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(default="abc@example.com", max_length=254)),
                ("waitlist_number", models.IntegerField(db_index=True, default=0)),
                (
                    "building_applied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="waitlist.Building",
                    ),
                ),
            ],
            options={
                "verbose_name": "queuer",
                "verbose_name_plural": "queuers",
                "unique_together": {("name", "contact_number", "building_applied")},
            },
        ),
    ]
