"""
Django settings for gamarried-research-scholar-portalbs project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import pymysql
pymysql.version_info = (1, 4, 2, 'final', 0)
pymysql.install_as_MySQLdb()
from .settings_config import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "oauth",
    "portal",
    "phonenumber_field",
    "widget_tweaks",
    "import_export",
]

# CRON_CLASSES = [
#     'married-research-scholar-portal.cron.MyCronJob'
# ]
# CRONJOBS = [
#     # ('5 * * * *', 'married-research-scholar-portal.cron.my_scheduled_job', '>> /tmp/scheduled_job.log'),
#     ('*/1 * */2 * *', 'portal.utils.send_notifs_to_students', '>> cronjobs.log'),
#     ('0 6 * * *', 'portal.utils.send_notifs_to_ARHCU', '>> notifs.log')
# ]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = "married-research-scholar-portal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "debug": DEBUG,
        },
    },
]

WSGI_APPLICATION = "married-research-scholar-portal.wsgi.application"

GOOGLE_APPLICATION_CREDENTIALS_PATH = "intern-kuku-cb7024b86822.json"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#    "development": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#    }
# }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"
PHONENUMBER_DEFAULT_REGION = "IN"

USE_I18N = True

# USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "generatedstaticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "upload")

X_FRAME_OPTIONS = "DENY"

LOGIN_URL = "oauth:login"
LOGOUT_URL = "oauth:logout"
LOGIN_REDIRECT_URL = "home"

AUTH_PROFILE_MODULE = "core.UserProfile"

DATE_INPUT_FORMATS = [
    '%Y-%m-%d'
]